### PR TITLE
Fixes background rectangle when highlighting

### LINKED ISSUE #20: highlight does not use the correct width / height for drawing background rect
This is related to / explanation for:
https://github.com/chafey/cornerstone/issues/16#issue-65320330

See:
http://stackoverflow.com/a/6722031/2638485

but basically this call is not correct if `scale != 1`:
```
context.rect(0, 0, context.canvas.clientWidth, context.canvas.clientHeight);
```
which it likely won't be after `setToPixelCoordinateSystem`.

### PR DESCRIPTION
**Pull request by cancan101**
Fixes #20

### CODE REVIEW

**Comment by cancan101** [comment]
See: https://rawgit.com/cancan101/cornerstoneTools/3c2db475da7c83a19f4ccbf8be4c8de4525ffd22/examples/highlight/index.html

**Comment by chafey** [comment]
@swederik Erik can you review this change this you contribute the rectangle tool?

**Comment by swederik** [comment]
Sorry for the slow reply, I didn't notice this

The fix works fine, but the PR also includes a regression of the included cornerstone library. The branch needs to be rebased from the master branch. To save @cancan101 some time, I just made a new PR #33 with the same fix but no regression problem.

**Comment by swederik** [comment]
This can be closed since #33 was merged.

**Pull request closed without merging**
