### PR TITLE
LengthTool now uses PixelSpacing provided by MetaDataProvider.

### PR DESCRIPTION
**Pull request by leonardorame**
Hi Erik, please review this PR and push to master if you consider it ok.

### CODE REVIEW

**Comment by swederik** [comment]
Hi Leonardo,

Maybe we can add a fallback like this? 

````javascript
var rowPixelSpacing = imagePlane.rowPixelSpacing || imagePlane.rowImagerPixelSpacing || eventData.image.columnPixelSpacing;
````

I just worry that some people won't have imagePlane metadata, so this will break.

I think you will also need to rebase on top of master again, sorry about that.

**Comment by leonardorame** [comment]
Done, could you check this out?.

**Comment by leonardorame** [comment]
Hi Erik, please, could you commit this?.

**Comment by swederik** [comment]
Sorry this took forever. Should be merged now.

**Pull request closed without merging**
