### PR TITLE
Add a preventCache flag to image stacks

### PR DESCRIPTION
**Pull request by swederik**
This is meant to prevent certain stacks from being cached. I haven't had time to test it yet, so don't merge it. Addresses issue #118.

### CODE REVIEW

**Comment by hiscodeness** [comment]
Looks good, I tested this PR against my current implementation and didn't notice any issues. 

In the code, I think it would be nice if repetition of 

    var loader;
    if (stackData.preventCache === true) {
          loader = cornerstone.loadImage(stackData.imageIds[newImageIdIndex]);
    } else {
          loader = cornerstone.loadAndCacheImage(stackData.imageIds[newImageIdIndex]);
    }
    loader.then(function(image) { ...

could be replaced with something like:

    cornerstone.loadImage(stackData.imageIds[newImageIdIndex], stackData.enableCache)

This would require a change in the core cornerstone API. Another option would be setting a loader function dynamically to stackData when the tool state is initially created. All tools using stackData would then call `stackData.loadImage(imageId, preventCache)` instead of the core cornerstone image loader functions.

**Comment by swederik** [comment]
Yep I agree it's annoyingly repetitive. I will discuss with @chafey about whether or not to change Cornerstone's loadImage API. The other idea is interesting but seems unnecessarily confusing to me.

Thanks for your help!

**Comment by swederik** [comment]
I'm just going to merge this for now. If / when we change the loadImage API we can revisit these changes.

**Comment by chafey** [comment]
FYI - My gut tells me we need to rethink the design approach to caching a bit, but I haven't had the time to do that yet, hence my lack of response.  Lets stick with the current API's for now and revisit this as part of a 2.0 type effort

**Pull request merged**
